{% set version = "1.1.0" %}

package:
  name: slicerator
  version: {{ version }}

source:
  fn: slicerator-v{{ version }}.tar.gz
  url: https://github.com/soft-matter/slicerator/archive/v{{ version }}.tar.gz
  sha256: a1fe86cb7c74d1a96fb0a899e8c5af1c5796dbff47ea88170a2e4ae6c2e73344

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip

  run:
    - python >=3.7

test:
  imports:
    - slicerator

about:
  home: http://github.com/soft-matter/slicerator
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A lazy-loading, fancy-sliceable iterable.

extra:
  recipe-maintainers:
    - conda-forge/tacaswell
    - danielballan
    - caspervdw
    - conda-forge/event-model
